### ISSUE TITLE
Failed to instantiate provider "esxi" to obtain schema

### ISSUE THREAD

**Issue by posone** [TribalNightOwl/okd4-esxi-helpernode-infra#1]
Hello,

firstly thank you have much for your work - it really helps me out. 
Unfortunately I am running into an issue when I have started helpernode.sh deploy - I am receiving error as follow:

> "Creating VMs in the ESXi server
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> 
> Terraform has been successfully initialized!
> 
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> 
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> 
> Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: permission denied"

Have you  had similar issues? I am trying to figure out what would be a real location of /usr/local/bin/terraform-provider-esxi_v1.7.0 because I do not see it on the local machine.

**Comment by posone** [comment]
Ok, I have found how you start this, I have added in the Dockerfile chmod 755 to  /usr/local/bin/terraform-provider-esxi_v1.7.0
but it did not help, now I can see that the format is not valid, looks like cpu architecture issue?
Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: exec format error

**Comment by TribalNightOwl** [comment]
I am running terraform inside a container as it seems you already found out.

I am not sure why you are seeing the problem you are seeing but let's start with the basic, I wrote a little simple test for the image I am using.

Please clone: https://github.com/TribalNightOwl/iac-tools-container

and execute:
`cd tests/terraform-esxi`
`./test.sh`

it should prompt you for your ESXi root password and then do a terraform init and plan.

**Comment by posone** [comment]
Hello! 
Thank you for fast response. I am receiving the same error. 

"# ./test.sh
Enter password for your ESXi server:
Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: permission denied"

**Comment by TribalNightOwl** [comment]
I was able to replicate your problem on a Mac: 

```
Enter password for your ESXi server: 
Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: permission denied
```

I am developing this on an Ubuntu Linux box.

**Comment by TribalNightOwl** [comment]
I found some reference to this kind of problem here:
https://github.com/josenk/terraform-provider-esxi/issues/106

and here:
https://github.com/josenk/terraform-provider-esxi/issues/71


I see that josenk has upgraded the provider and it is now offered from the Terraform registry when using Terraform 0.13.x maybe that version will help with this?  I don't know but I will update this container to use that.

If the above doesn't work the only solution I can offer is to run this in a Linux VM inside your Mac or recompile the provider as shown in those links I added here.

**Comment by posone** [comment]
It's interesting, because I do not use mac, I am working on this project on Centos8 (CentOS Linux release 8.0.1905). Ok then, I will try to spin up an Ubuntu VM on Monday then, I also have Centos7, will try there as well. I did not suspect that the local system could be an issue here, especially that you are using docker.  I will let you know, thank you for your findings and hard work which you are doing. Cheers.

**Comment by TribalNightOwl** [comment]
Wow, yes, this is interesting! 

I will try on Centos 8 later.

You are welcome and thanks for the feedback.

**Comment by TribalNightOwl** [comment]
The new version of the provider with the new version of Terraform works in Centos 8.

```
$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core) 
```

This is what I got:
```
$ ./test.sh
Enter password for your ESXi server:
Initializing the backend...

Initializing provider plugins...
- Finding latest version of josenk/esxi...
- Installing josenk/esxi v1.7.1...
- Installed josenk/esxi v1.7.1 (self-signed, key ID A3C2BB2C490C3920)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* josenk/esxi: version = "~> 1.7.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

                                                                                                                                              
If you ever set or change modules or backend configuration for Terraform,                                                                     
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.  
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.                    
                                                 
                          
------------------------------------------------------------------------
                                                          
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
                                                    
Terraform will perform the following actions:       
                                                    
  # esxi_guest.myvirtualmachine will be created
  + resource "esxi_guest" "myvirtualmachine" {
      + boot_disk_size         = "200"
      + boot_disk_type         = "thin"
      + disk_store             = "alldisks"
      + guest_name             = "myvirtualmachine"
      + guest_shutdown_timeout = (known after apply)
      + guest_startup_timeout  = (known after apply)                 
      + guestos                = "centos-64"
      + id                     = (known after apply)           
      + ip_address             = (known after apply)                          
      + memsize                = "8192"           
      + notes                  = (known after apply)
      + numvcpus               = "4"                                         
      + ovf_properties_timer   = (known after apply)
      + power                  = "off"
      + resource_pool_name     = (known after apply)                         
      + virthwver              = "13"                                         
    }                                                              

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```


Make sure you remove the old image of iactools before running this test.

docker rmi tribrhy/iactools:latest

I will add that to the test.sh script.

**Comment by TribalNightOwl** [comment]
Just to complete the circle I decided to test the old image on the Centos 8 VM I created and it did NOT exhibit the problem you reported:

```
[user01@centos8 terraform-esxi]$ docker rmi tribrhy/iactools:1.0
Untagged: tribrhy/iactools:1.0
Untagged: tribrhy/iactools@sha256:10b18a43646188116d71193ba0da328cc374c726e77ba515cd99f1092d830175
Deleted: sha256:899e15de3ed0f240a3b91c0cde4ccf86608d174579553b96d1d185411b26a671
Deleted: sha256:d0b3cae4bfbc04262a0ac5977be746e6f34931647299bdf55b96ae78f7485b18
Deleted: sha256:739eb2a2bdad970cfdec95817673b1a1c0bf9f09cc5840f23c78c97287c8303f
Deleted: sha256:a7ad4e1672bd7ff726e7d6db7983eb6050543f774bbe5a7d7906d06f9662e3b8
Deleted: sha256:7515ee845913c8df9826c988341a09e0240e291c66bdc436a067e070d7910a1f
Deleted: sha256:50ebe6a0675f1ed7ca499a2ec7d8cc993d495dd66ca1035c218ec5efcb6fbb8c
Deleted: sha256:2515e0ecfb82d58c004c4b53fcf9230d9eca8d0f5f823c20172be01eec587ccb
Deleted: sha256:ce30112909569cead47eac188789d0cf95924b166405aa4b71fb500d6e4ae08d
```

Here I updated `test.sh` and `main.tf` to use iactools:1.0


```
[user01@centos8 terraform-esxi]$ ./test.sh                                      
Trying to remove the image to ensure we are testing the latest
Error: No such image: tribrhy/iactools:latest
Enter password for your ESXi server: Unable to find image 'tribrhy/iactools:1.0' locally
1.0: Pulling from tribrhy/iactools
3ff22d22a855: Pull complete
e7cb79d19722: Pull complete
323d0d660b6a: Pull complete
b7f616834fd0: Pull complete
f93e8522a3f0: Pull complete
8dde8677bc3f: Pull complete
1ff58ee2cb78: Pull complete
Digest: sha256:10b18a43646188116d71193ba0da328cc374c726e77ba515cd99f1092d830175
Status: Downloaded newer image for tribrhy/iactools:1.0

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # esxi_guest.myvirtualmachine will be created
  + resource "esxi_guest" "myvirtualmachine" {
      + boot_disk_size         = "200"
      + boot_disk_type         = "thin"
      + disk_store             = "alldisks"
      + guest_name             = "myvirtualmachine"
      + guest_shutdown_timeout = (known after apply)
      + guest_startup_timeout  = (known after apply)
      + guestos                = "centos-64"
      + id                     = (known after apply)
      + ip_address             = (known after apply)
      + memsize                = "8192"
      + notes                  = (known after apply)
      + numvcpus               = "4"
      + ovf_properties_timer   = (known after apply)
      + power                  = "off"
      + resource_pool_name     = (known after apply)
      + virthwver              = "13"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

So, after seeing this, using the latest might not fix your issue.

Are you sure nobody switched your machine for a Mac?   ;)

**Comment by posone** [comment]
That's really strange.. Tomorrow I will do some tests on Centos7 and Ubuntu, I will also try to use the fix on Centos8. 
Heh, I am sure. ;) these VMs run on ESX, I am controlling the OS.

**Comment by posone** [comment]
Hello,

so.. I am not sure why but it does not work on my centos8. Anyway - I have spin up another VM with Ubuntu 20.4 - at least terraform is working now. :) I have found few minor bugs, just for your information. 

- folder files have to be created manually before we start deploy
- beside .env and playbooks/vars.yaml - there is a need to adjust hosts file
- where something goes wrong and we want to do destroy/do new deploy - the docker image (nginx) is not removing itself and the folder /tmp/kickstart-helpernode/ have to be removed manually - these two items blocking script when it's re-run
- I think you should add in the requirements that VMRC should be installed on the machine including GUI 

For now I am struggling with vmrc and display settings on ubuntu, I hope that after that the rest should go smoothly. Let's keep this issue open just for couple more days just in case. 
Thank you!!

**Comment by posone** [comment]
Hello!
I am still working on that, but I think I am close. :) 
In this step: playbooks/clone-repo.yaml
in the repo (git clone --depth 1 --branch ocp-4.5.2-tno1 https://github.com/TribalNightOwl/ocp4-helpernode) in the folder files there is no pull-secret.json file. That's why the job is failing in the next step when the file is expected. 
I will try to copy over my file before this step and hopefully it will work.

**Comment by TribalNightOwl** [comment]
Thanks for the feedback @posone.

I will work on some of those items you pointed out, but feel free to open independent issues or even submitting PRs.
